version: '2'
services:

  moodle:
    image: docker.io/kazuhisya/moodle
    links:
      - moodle_db
    environment:
      TZ: Asia/Tokyo
      POSTGRES_HOST: moodle_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle
      PGPASSWORD: moodle
      MOODLE_URL: "http://localhost:8080/moodle"
      MOODLE_LANG: ja                              # moodle lang
      MOODLE_ADMINUSR: admin                       # moodle admin
      MOODLE_ADMINPWD: admin                       # moodle admin pw
      MOODLE_ADMINEML: root@localhost.localdomain  # moodle admin email
      MOODLE_SITENAME: "TestMoodle"                # site name
      MOODLE_SITESHORT: "TestMoodl"                # site short name
    ports:
      - 8080:80
    volumes:
      - .data/moodledata:/var/www/moodledata

  moodle_db:
    image: docker.io/postgres:alpine
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: moodle
      POSTGRES_USER: moodle
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: moodle
    ports:
      - 5432:5432
    volumes:
      - .data/moodledb:/var/lib/postgresql/data/pgdata
